name: Deploy Slim PHP 3 Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies with Composer
        run: composer install

      - name: Deploy to Apache
        run: |
          ssh gambol@20.11.64.99 'cd /var/www/html/akademik-asia & git pull origin main'
