name: Deploy Slim PHP 3 Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Apache
        run: |
          sudo cp -r /var/www/html/akademik-asia/. /var/www/html/
