name: Deploy Slim PHP 3 Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH and Git
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Apache
        run: |
          ssh gambol@20.11.64.99 'cd /var/www/html/akademik-asia && git pull origin main'
